name: Update Weather
on:
  schedule:
    - cron: '0 */3 * * *' # every 3 hours
  workflow_dispatch:
permissions:
  contents: write
jobs:
  update-weather:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run weather generator
        uses: huantt/weather-forecast@v1.0.5
        with:
          city: "Raleigh"
          country: "US"
          days: 1
          units: "metric"
          weather-api-key: ${{ secrets.WEATHER_API_KEY }}
          template-file: 'README.md.template'
          out-file: 'README.md'
